/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SensitivityProfile = IDL.Record({
  'freeLook' : IDL.Nat,
  'sniperScope' : IDL.Nat,
  'scope2x' : IDL.Nat,
  'scope4x' : IDL.Nat,
  'general' : IDL.Nat,
  'deviceTier' : IDL.Text,
  'redDot' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getSensitivity' : IDL.Func([IDL.Text], [SensitivityProfile], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SensitivityProfile = IDL.Record({
    'freeLook' : IDL.Nat,
    'sniperScope' : IDL.Nat,
    'scope2x' : IDL.Nat,
    'scope4x' : IDL.Nat,
    'general' : IDL.Nat,
    'deviceTier' : IDL.Text,
    'redDot' : IDL.Nat,
  });
  
  return IDL.Service({
    'getSensitivity' : IDL.Func([IDL.Text], [SensitivityProfile], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };